### ISSUE TITLE
Please add a readme

### ISSUE THREAD

**Issue by ohadlevy** [kubevirt/cdi-operator#12]
For new users seeing this repository for the first time, its very hard to understand what its about or how to use or contribute to it.

- [ ] Add a welcome / what this is about section
- [ ] Add a how to install / use etc
- [ ] Add a how to contribute section

if by the time this get implemented we have a working CI, it would be nice to add the CI status to the readme as well.

**Comment by alexxa** [comment]
+ Add repo description. Now it's: "No description, website, or topics provided. " right under the repo Title.
